// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yitldryumpmhzymxoioq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpdGxkcnl1bXBtaHp5bXhvaW9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MTUwNTEsImV4cCI6MjA2NDE5MTA1MX0.7ZkPZdM0TpRRgERYWWCRPKfVhiAWSzgJQqM8ZlVuQZ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);